name: pre

on:
  push:
    tags:
     - v*

jobs:
  pre-release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo pre-released ${{ github.event.release.tag_name }}
         echo pre-released ${{ github.event.release.action }}
