name: released

on:
  release:
    types:
      - released

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo released ${{ github.event.release.tag_name }}
          gh release edit ${{ github.event.release.tag_name }} --latest
