name: released

on:
  release:
    types:
      - released

jobs:
  release:
    runs-on: ubuntu-22.04
    needs: [application-deployment-approve]
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo released ${{ github.event.release.tag_name }}
          gh release edit ${{ github.event.release.tag_name }} --latest
